server:
  port: 8090
  servlet:
    context-path: /form-builder
spring:
  application:
    name: Form Builder
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: create