server:
  port: 8090
  servlet:
    context-path: /form-builder
spring:
  application:
    name: Form Builder 2.0
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto:
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true